/** Telegram channel descriptions are limited to 255 characters. */
export const REPORTING_CHANNEL_DESCRIPTION =
  "Official Naman IAS executive business reporting. Figures use IST. Collections = actual receipts only. Full metric definitions are in the pinned Reporting Definitions message.";

export function reportingDefinitionsHtml(): string {
  return [
    "<b>NAMAN IAS — REPORTING DEFINITIONS</b>",
    "<i>Asia/Kolkata. Today runs from midnight until the report time.</i>",
    "",
    "<b>Collections</b>",
    "Actual money received on a paid receipt. Course fee, outstanding balance and future installments are excluded.",
    "",
    "<b>Online Collection</b>",
    "Payments successfully received through the portal or payment gateway.",
    "",
    "<b>Staff Recorded Collection</b>",
    "Cash, UPI, bank transfer or another legitimate payment manually recorded by authorized academy staff. A receipt is counted once, either online or staff recorded.",
    "",
    "<b>Paying Students</b>",
    "Unique students with at least one qualifying payment in the period.",
    "",
    "<b>Receipt Mix</b>",
    "The same collected rupees, split by what the receipt was for. Unclassified receipts sit in Other.",
    "",
    "<b>Unique Logins</b>",
    "Distinct students with a real sign-in. A second sign-in does not add another. Staff and leads are excluded.",
    "",
    "<b>Login Events</b>",
    "Total authentication events. One student can create several.",
    "",
    "<b>Active Students</b>",
    "Distinct authenticated students who signed in or opened the portal, a class or a course that day, including a session that was already active.",
    "",
    "<b>Returning Active</b>",
    "Active students who were not newly created that day.",
    "",
    "<b>New Accounts</b>",
    "New legitimate student accounts created in the period.",
    "",
    "<b>30-day avg / 90-day avg</b>",
    "Average unique daily logins across the previous 30 or 90 complete IST days, including days with zero logins. Today is excluded.",
    "",
    "<b>Sent SMS</b>",
    "SMS the provider accepted, or that later received a delivery or failure receipt. A delivery callback is not a second send. A new retry counts again.",
    "",
    "<b>Delivered SMS</b>",
    "Confirmed delivered by a provider delivery receipt.",
    "",
    "<b>Failed SMS</b>",
    "Confirmed failed.",
    "",
    "<b>Queued SMS</b>",
    "Still waiting for the provider to accept them.",
    "",
    "<b>Pending SMS</b>",
    "Accepted by the provider, with no delivery or failure receipt yet.",
    "",
    "<b>Webinar registrations</b>",
    "Distinct paid seats. New today is a seat whose first paid receipt was created today, not a later payment on an older seat.",
    "",
    "<b>Registration sources</b>",
    "The attribution stamp stored on the paid receipt. Blank stamps are Unknown. They are not guessed.",
    "",
    "<b>Outstanding Fees</b>",
    "Money still owed. This is not collected revenue.",
    "",
    "<b>Payment Attention</b>",
    "Failed attempts today. Unresolved means no later successful payment for the same item. Later paid is not an open issue.",
  ].join("\n");
}
