// Generates docs/sms-dlt-templates.md (a committed SNAPSHOT of the DLT Approval
// Sheet). The LIVE export in the portal (Templates tab) is produced by
// lib/sms/dlt.ts, and this script now calls that same code instead of keeping
// its own copy of the template list and the {token} regex.
//
// It used to duplicate both. The copies drifted: the local SEED was three
// templates behind lib/sms/templates.ts, and the local matcher was the
// lowercase-only `/\{([a-z_]+)\}/g` that caused the Installment Reminder
// incident, so any mixed-case token would have been left unconverted in the
// exported body while the mapping still counted it.
//
// Run: node --import tsx scripts/gen-sms-dlt.mjs
import { writeFileSync, mkdirSync } from "node:fs";
import { buildDltRows, dltToMarkdown } from "../lib/sms/dlt.ts";

const rows = buildDltRows();
const md = dltToMarkdown(rows).replace(
  "# SMS DLT Approval Sheet — Naman Sharma IAS Academy\n",
  "# SMS DLT Approval Sheet — Naman Sharma IAS Academy\n\n" +
    "> SNAPSHOT generated by `scripts/gen-sms-dlt.mjs`. The live, always-current export is in the portal: " +
    "**Admin → Communications → SMS Mission Control → Templates → Export DLT Approval Sheet**.\n",
);

mkdirSync("docs", { recursive: true });
writeFileSync("docs/sms-dlt-templates.md", md + "\n");
console.log("Wrote docs/sms-dlt-templates.md with", rows.length, "templates.");
