import { MapPin, PackageCheck, ShoppingBag, Truck } from "lucide-react";

const STEPS = [
  {
    n: "1",
    t: "Place your order",
    d: "Choose one or more subjects and confirm your delivery address.",
    Icon: ShoppingBag,
  },
  {
    n: "2",
    t: "We pack it securely",
    d: "Our team prepares and securely packs your printed notes.",
    Icon: PackageCheck,
  },
  {
    n: "3",
    t: "Track your package",
    d: "Once shipped, a tracking number is generated by our delivery partner so you can follow your order.",
    Icon: Truck,
  },
  {
    n: "4",
    t: "Delivered to you",
    d: "Delivery time depends on your city and PIN code and may vary by courier partner.",
    Icon: MapPin,
  },
];

export default function ShippingStory({ compact = false }: { compact?: boolean }) {
  return (
    <div id={compact ? undefined : "delivery"} className={compact ? "" : "rounded-[28px] border border-[var(--ca-navy)]/8 bg-[linear-gradient(180deg,#ffffff_0%,#fbf8f2_100%)] px-5 py-7 sm:px-7"}>
      <p className="ca-eyebrow text-[var(--ca-gold-dark)]">Physical delivery</p>
      <h2 className={`${compact ? "mt-2 text-xl" : "mt-2 text-2xl"} font-heading font-bold text-[var(--ca-navy)]`}>
        From Order to Your Door
      </h2>
      <p className="mt-2 max-w-xl text-sm text-[var(--ca-navy)]/58">
        Order your notes and track the package until it reaches you.
      </p>
      <ol className={`ns-delivery-steps mt-6 grid gap-5 ${compact ? "" : "sm:grid-cols-2 lg:grid-cols-4"}`}>
        {STEPS.map((s) => (
          <li key={s.t} className="relative">
            <div className="flex items-center gap-2">
              <span className="grid h-7 w-7 place-items-center rounded-full border border-[var(--ca-gold)]/45 bg-white font-heading text-xs font-extrabold text-[var(--ca-navy)]">
                {s.n}
              </span>
              <s.Icon size={16} strokeWidth={1.7} className="text-[var(--ca-gold-dark)]" aria-hidden="true" />
            </div>
            <p className="mt-2 font-heading text-[13px] font-extrabold uppercase tracking-[0.08em] text-[var(--ca-navy)]">
              {s.t}
            </p>
            <p className="mt-1 text-sm leading-relaxed text-[var(--ca-navy)]/60">{s.d}</p>
          </li>
        ))}
      </ol>
    </div>
  );
}
